package Controle;
// Generated 28/06/2015 16:31:30 by Hibernate Tools 3.6.0



/**
 * Atividade generated by hbm2java
 */
public class Atividade  implements java.io.Serializable {


     private int id;
     private String nome;
     private String tipo;
     private String sdata;
     private Float valor;
     private Float nota;

    public Atividade() {
    }

	
    public Atividade(int id, String nome, String tipo, String sdata) {
        this.id = id;
        this.nome = nome;
        this.tipo = tipo;
        this.sdata = sdata;
    }
    public Atividade(int id, String nome, String tipo, String sdata, Float valor, Float nota) {
       this.id = id;
       this.nome = nome;
       this.tipo = tipo;
       this.sdata = sdata;
       this.valor = valor;
       this.nota = nota;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getSdata() {
        return this.sdata;
    }
    
    public void setSdata(String sdata) {
        this.sdata = sdata;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Float getNota() {
        return this.nota;
    }
    
    public void setNota(Float nota) {
        this.nota = nota;
    }




}


