package Controle;
// Generated 28/06/2015 16:31:30 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private int id;
     private String nome;
     private String ementa;
     private String caragaHoraria;
     private Set turmas = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(int id, String nome, String ementa, String caragaHoraria) {
        this.id = id;
        this.nome = nome;
        this.ementa = ementa;
        this.caragaHoraria = caragaHoraria;
    }
    public Disciplina(int id, String nome, String ementa, String caragaHoraria, Set turmas) {
       this.id = id;
       this.nome = nome;
       this.ementa = ementa;
       this.caragaHoraria = caragaHoraria;
       this.turmas = turmas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmenta() {
        return this.ementa;
    }
    
    public void setEmenta(String ementa) {
        this.ementa = ementa;
    }
    public String getCaragaHoraria() {
        return this.caragaHoraria;
    }
    
    public void setCaragaHoraria(String caragaHoraria) {
        this.caragaHoraria = caragaHoraria;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


