package Controle;
// Generated 28/06/2015 16:31:30 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private int id;
     private String nome;
     private String cpf;
     private String departamento;
     private Set turmas = new HashSet(0);

    public Professor() {
    }

	
    public Professor(int id, String nome, String cpf, String departamento) {
        this.id = id;
        this.nome = nome;
        this.cpf = cpf;
        this.departamento = departamento;
    }
    public Professor(int id, String nome, String cpf, String departamento, Set turmas) {
       this.id = id;
       this.nome = nome;
       this.cpf = cpf;
       this.departamento = departamento;
       this.turmas = turmas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


