package Controle;
// Generated 28/06/2015 16:31:30 by Hibernate Tools 3.6.0



/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private int id;
     private Aluno aluno;
     private Disciplina disciplina;
     private Professor professor;
     private String ano;
     private String periodo;
     private String slocal;
     private String horario;
     private Integer nvagas;

    public Turma() {
    }

	
    public Turma(int id, Aluno aluno, Disciplina disciplina) {
        this.id = id;
        this.aluno = aluno;
        this.disciplina = disciplina;
    }
    public Turma(int id, Aluno aluno, Disciplina disciplina, Professor professor, String ano, String periodo, String slocal, String horario, Integer nvagas) {
       this.id = id;
       this.aluno = aluno;
       this.disciplina = disciplina;
       this.professor = professor;
       this.ano = ano;
       this.periodo = periodo;
       this.slocal = slocal;
       this.horario = horario;
       this.nvagas = nvagas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getSlocal() {
        return this.slocal;
    }
    
    public void setSlocal(String slocal) {
        this.slocal = slocal;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public Integer getNvagas() {
        return this.nvagas;
    }
    
    public void setNvagas(Integer nvagas) {
        this.nvagas = nvagas;
    }




}


